version = "1.1.6"

[format]
# Deduplicate icons if enable.
# A superscripted counter will be added.
dedup = true
# dedup_inactive_fullscreen = false # dedup more
# window delimiter
# delim = " "

# available formatter:
# {counter_sup} - superscripted count of clients on the workspace, and simple {counter}, {delim}
# {icon}, {client}
# workspace formatter
workspace = "{id}:{delim}{clients}" # {id}, {delim} and {clients} are supported
workspace_empty = "{id}" # {id}, {delim} and {clients} are supported
# client formatter
client = "{icon}"
client_active = "{icon}"

# deduplicate client formatter
# client_fullscreen = "[{icon}]"
# client_dup = "{client}{counter_sup}"
# client_dup_fullscreen = "[{icon}]{delim}{icon}{counter_unfocused}"
# client_dup_active = "*{icon}*{delim}{icon}{counter_unfocused}"

# [initial_class]
"DEFAULT" = "ï™ {class}: {title}"
# "(?i)Kitty" = "term"

# [initial_class_active]
# "(?i)Kitty" = "*TERM*"

# regex captures support is supported
# "emerge: (.+?/.+?)-.*" = "{match1}"

# [title_in_class."(?i)firefox"]
# "(?i)twitch" = "<span color='purple'>ğŸ¤–</span>"

# [title_in_class_active."(?i)firefox"]
# "(?i)twitch" = "<span color='purple'>ğŸ¤–</span>"

# [title_in_initial_class."(?i)kitty"]
# "(?i)neomutt" = "neomutt"

# [initial_title_in_class."(?i)kitty"]
# "(?i)neomutt" = "neomutt"

# [initial_title_in_initial_class."(?i)kitty"]
# "(?i)neomutt" = "neomutt"

# [initial_title."(?i)kitty"]
# "zsh" = "Zsh"

# [initial_title_active."(?i)kitty"]
# "zsh" = "*Zsh*"

# Add your applications that need to be exclude
# The key is the class, the value is the title.
# You can put an empty title to exclude based on
# class name only, "" make the job.
[exclude]
"" = "^$" # prevent displaying icon for empty class
"(?i)fcitx" = ".*" # will match all title for fcitx
"(?i)TestApp" = "" # will match all title for TestApp
aProgram = "^$" # will match null title for aProgram
"[Ss]team" = "^(Friends List.*)?$" # will match Steam friends list plus all popups (empty titles)

[workspaces_name]
0 = "zero"
1 = "one"
2 = "two"
3 = "three"
4 = "four"
5 = "five"
6 = "six"
7 = "seven"
8 = "eight"
9 = "nine"
10 = "ten"

[class]
DEFAULT = "*"
"(?i)alacritty" = "<span> ~ </span>"
"(?i)chrome" = "<span>ï‰¨  </span>"
"(?i)deluge" = "<span>ï€™ </span>"
"(?i)chromium" = "<span>ï‰¨  </span>"
"(?i)firefox" = "<span> ï‰© </span>"
".*transmission.*" = "<span>ï€™ </span>"
discord = "<span>ï’ </span>"
libreoffice-calc = "<span>ï‡ƒ </span>"
libreoffice-impress = "<span>ï‡„ </span>"
libreoffice-startcenter = "<span>ï‡‚ </span>"
libreoffice-writer = "<span>ï‡‚ </span>"
mpv = "<span>ï‹ </span>"
nemo = "<span>ï¼ </span>"
neomutt = "<span>ïƒ  </span>"
nm-connection-editor = "<span>ïƒ¨ </span>"
pavucontrol = "<span>ïµ </span>"
slack = "<span>ï¯ </span>"
spotify = "<span>ï†¼ </span>"
steam = "<span>ï†¶ </span>"
udiskie = "ï‚ "
vimiv = "ïŒ‚"
vlc = "<span>ï…„ </span>"
whatsapp-desktop = "<span>ïˆ² <span>"
whatsapp-nativefier-d52542 = "<span>ïˆ² </span>"
