console_title_template = "{{ .Folder }}"
version = 3

[transient_prompt]
background = "transparent"
foreground = "#cccccc"
template = "{{ now | date \"15:04:05\" }} {{ if gt .Code 0 }}\u001b[38;2;224;108;117mâœ—{{ else }}\u001b[38;2;152;195;121mâœ“{{ end }} \u001b[38;2;224;108;117mâ¯\u001b[0m "

[[blocks]]
type = "prompt"
alignment = "left"

[[blocks.segments]]
type = "path"
style = "plain"
foreground = "#99ffaa"
template = "{{ .Path }}{{ if not .Writable }}ğŸ”’ {{ end }}"
foreground_templates = [
    "{{ if gt .Code 0 }}#ff9999{{ end }}"
]

[blocks.segments.properties]
cache_duration = "none"
folder_icon = "ğŸ”’"
folder_separator_icon = "/"
style = "full"

# [[blocks.segments]]
# type = "jujutsu"
# style = "plain"
# foreground = "yellow"
# template = " ï‡º{{.ChangeID}} {{.ClosestBookmarks}}{{if .Working.Changed}} ï„ {{ .Working.String }}{{ end }}"
# foreground_templates = [
#     "{{ if .Working.Changed }}#ff7733{{ end }}"
# ]

[[blocks.segments]]
type = "git"
style = "plain"
foreground = "yellow"
template = "{{ if not .Segments.Jujutsu }} {{ if or (.Working.Changed) (.Staging.Changed) }}{{ end }}{{ if .Working.Untracked }}\ueadc {{ end }}{{ if .Working.Modified }}\ueb43 {{ end }}{{ if .Working.Deleted }}â¡ {{ end }}{{ if .Staging.Added }}+{{ .Staging.Added }} {{ end }}{{ if gt .Ahead 0 }}A {{ end }}{{ if gt .Behind 0 }}B {{ end }}{{ if and (gt .Ahead 0) (gt .Behind 0) }}D {{ end }}{{ if and (eq .Ahead 0) (eq .Behind 0) (not .Working.Changed) (not .Staging.Changed) }}\uf058 {{ end }}{{.HEAD}}{{end}}"
foreground_templates = [
    "{{ if or (.Working.Changed) (.Staging.Changed) }}#ff7733{{ end }}"
]

[blocks.segments.properties]
branch_icon = "\ue725 "
cache_duration = "none"
commit_icon = ""
fetch_status = true
tag_icon = "ğŸ·"

[[blocks.segments]]
type = "text"
style = "plain"
foreground = "yellow"
template = " â¯ "

[blocks.segments.properties]
cache_duration = "none"

